### ISSUE TITLE
zindex

### ISSUE THREAD

**Issue by SCrid2000** [simonwhitaker/github-fork-ribbon-css#13]
To make it work with JQueryMobile (and I would assume other frameworks as well), a z-index should be added to
.github-fork-ribbon-wrapper.left
.github-fork-ribbon-wrapper.right
.github-fork-ribbon-wrapper.left-bottom 
.github-fork-ribbon-wrapper.right-bottom 

The z-index needs to be 1001 or higher.

**Comment by simonwhitaker** [comment]
Good call, thanks.

Where did you get the 1001 from? Just curious, I'd like to add a reference in the code that me-in-5-years remembers where it came from. :)

**Comment by SCrid2000** [comment]
The z-index for the top/bottom headers in JQuery Mobile is 1000, so 1001 ensures that the ribbon is higher than them :+1:
