### ISSUE TITLE
demo doesn't work on IE7, IE8, or IE9

### ISSUE THREAD

**Issue by eedeebee** [simonwhitaker/github-fork-ribbon-css#14]
I see different bugs in each browser.  Let me know if you need details.

**Comment by simonwhitaker** [comment]
Details would be good. Pull requests even better. :-)

**Comment by eedeebee** [comment]
I will send you some screen shots next time I'm in front of a windows box.    Pull request you won't see, since my solution was to use an image that I could generate via http://oojits.com/info/img/corner-ribbons/ portable and reliable and easy enough thanks to oojits.

**Comment by simonwhitaker** [comment]
OK, IE 8 and 9 are fixed. No plan to fix IE7.
