### ISSUE TITLE
Doesn't work on IE9 (and suggestion to fix it)

### ISSUE THREAD

**Issue by henrygotmojo** [simonwhitaker/github-fork-ribbon-css#18]
Demo looks good on IE9 but the ribbon is not clickable.

Followings are my suggestion to fix it:
1.  Remove "filter" of ".github-fork-ribbon" in "gh-fork-ribbon.css"
2.  Add "-ms-transform: rotate(...)" in "gh-fork-ribbon.css"
3.  Do not include "gh-fork-ribbon.ie.css" for IE9

**Comment by simonwhitaker** [comment]
Hi,

Sorry for _such_ a late response to this! I think this one's covered in https://github.com/XhmikosR/github-fork-ribbon-css/commit/abf26e1bdfaf1a84d789b6c5c87b8b9345962317, which I'm about to merge.

All the best,

Simon
