### ISSUE TITLE
Branches question

### ISSUE THREAD

**Issue by XhmikosR** [simonwhitaker/github-fork-ribbon-css#22]
Have you thought about just using a gh-pages branch instead of 2 and removing the master one? Here it makes sense to do this.

**Comment by simonwhitaker** [comment]
Good question! I've made gh-pages the default and removed master.

**Comment by XhmikosR** [comment]
The master branch is still in the repository. Also, should I create a new PR rebases against the gh-pages branch?

**Comment by simonwhitaker** [comment]
No thanks, I've merged the PR and deleted the master branch (again!) 

Thanks!
