### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by XhmikosR** [simonwhitaker/github-fork-ribbon-css#23]
I wonder if you could publish the package to bower?

**Comment by simonwhitaker** [comment]
What's bower?

**Comment by XhmikosR** [comment]
https://github.com/bower/bower

**Comment by simonwhitaker** [comment]
Done!

```
$ bower lookup github-fork-ribbon-css
github-fork-ribbon-css git://github.com/simonwhitaker/github-fork-ribbon-css.git
```

Thanks for the suggestion. :smile:

**Comment by XhmikosR** [comment]
No problem, glad you find it useful :)

BTW, the version I used was just an example, you can bump it if you want.

Now, the only real issue left is IE <= 8...
