### ISSUE TITLE
Use same font as original ribbons

### ISSUE THREAD

**Issue by stuartpb** [simonwhitaker/github-fork-ribbon-css#27]
The original ribbon used the K-Type Collegiate font - would be nice to put that to use with these.

It looks like someone's already compiled the font for web embedding, so it'd just be a matter of ganking these and perhaps hosting/hotlinking them via gh-pages:

https://github.com/tubbo/psychedeli.ca/tree/master/app/assets/fonts

Indeed, seeing as how it's been six years since the original publication of the image ribbons, which haven't been revisited even now that the official GitHub font brand has changed, it wouldn't be bad to see this embraced by upstream...

**Comment by simonwhitaker** [comment]
It's a nice idea Stuart, but Collegiate is a commercial font (albeit one that's made available for free for non-commercial use) and I can't find any mention on K-Type's website of an officially prepared or sanctioned web font. If you know differently then please let me know. My guess is that K-Type are unaware of the repo you linked to, and that it may well infringe their copyright.
