### ISSUE TITLE
Different colors

### ISSUE THREAD

**Issue by neersighted** [simonwhitaker/github-fork-ribbon-css#3]
If you look [here](https://github.com/blog/273-github-ribbons), you'll see that the colors are included in the filenames. After #1 is merged, I can implement colors using the colors that Github used.

**Comment by simonwhitaker** [comment]
Thanks for your help so far! I've made some additional changes so if you merge from master before you submit the diffs for this one it'll keep things nice and clean.

**Comment by neersighted** [comment]
No problem!

**Comment by neersighted** [comment]
I'm waiting to see if #10 will be merged before starting on this. Selector nesting is so nice in SCSS.
