### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by PeterDaveHello** [simonwhitaker/github-fork-ribbon-css#32]
Chrome will blocked normalize.min.css automatically because the website use https protocol but the lib doesn't, the warning in Chrome's console :

> The page at 'https://simonwhitaker.github.io/github-fork-ribbon-css/' was loaded over HTTPS, but ran insecure content from 'http://oss.maxcdn.com/libs/normalize-css/3.0.0/normalize.min.css': this content should also be loaded over HTTPS.

**Comment by XhmikosR** [comment]
Well, the reason for this choice, is that protocol relative URLs don't work via file. And I didn't want to make Jekyll a requirement for local development back then.
