### ISSUE TITLE
label position incorrect for yeoman generated angular app

### ISSUE THREAD

**Issue by typekpb** [simonwhitaker/github-fork-ribbon-css#34]
not sure, where the problem is, just tested with yeoman generated angular app and I see following:

![fork-me-on-gh](https://cloud.githubusercontent.com/assets/499820/4974368/820c3036-68cb-11e4-8a41-5aa6af52ef4f.png)

steps to reproduce:

```
  mkdir fork-me-on-gh
  cd fork-me-on-gh
  yo angular
  bower install --save github-fork-ribbon-css
  grunt serve
```

Afterwards, just replaced (in `fork-me-on-gh/app/index.html`):

```
  <body ng-app="forkMeOnGhApp">
```

with: 

```
  <body ng-app="forkMeOnGhApp">
  <div class="github-fork-ribbon-wrapper left">
        <div class="github-fork-ribbon">
            <a href="https://github.com/simonwhitaker/github-fork-ribbon-css">Fork me on GitHub</a>
        </div>
      </div>
```

**Comment by typekpb** [comment]
not sure why, but copy-pasting (from the official css) the following style to my css:

```
.github-fork-ribbon-wrapper.left .github-fork-ribbon {
  top: 42px;
  left: -43px;
}
```

solved it for me.

Sounds like influenced by some other css that got in the way.

**Comment by brunowego** [comment]
+1 `generator-webapp`

Solution of @typekpb worked.

**Comment by hugovk** [comment]
Could this related to https://github.com/simonwhitaker/github-fork-ribbon-css/issues/37?

i.e. does the generated HTML end up something like this? (CDN or local, it's not important.)

``` html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.1.1/gh-fork-ribbon.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.1.1/gh-fork-ribbon.ie.min.css" />
```

If so, you'll end up loading the IE9 CSS for non-IE9 browsers. The second CSS needs to be in a conditional, something like:

``` html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.1.1/gh-fork-ribbon.min.css" />
<!--[if lt IE 9]>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.1.1/gh-fork-ribbon.ie.min.css" />
<![endif]-->
```

**Comment by simonwhitaker** [comment]
Closing this one out on the rash, idle assumption that #37 probably fixes it. Please feel free to submit a pull request if that's not the case.
