### ISSUE TITLE
add usage instructions to homepage

### ISSUE THREAD

**Issue by afeld** [simonwhitaker/github-fork-ribbon-css#43]
After including the stylesheets, it's not clear how to add the ribbons to the page. A more experienced user can inspect the page and figure it out, but would be better to walk users through it explicitly. Thanks!

**Comment by hugovk** [comment]
I've added this in PR https://github.com/simonwhitaker/github-fork-ribbon-css/pull/46.

In the meantime you can see it on the demo page: https://simonwhitaker.github.io/github-fork-ribbon-css/.

**Comment by afeld** [comment]
Nice! Maybe worth adding the list of supported CSS classes, and how to customize the color?

**Comment by simonwhitaker** [comment]
Fixed in #46
