### ISSUE TITLE
Update bower version

### ISSUE THREAD

**Issue by JPeer264** [simonwhitaker/github-fork-ribbon-css#55]
Please update the version on `bower`. It is still on `0.2.0` but I need `0.2.1` with the `box-sizing` fix.

**Comment by JPeer264** [comment]
@simonwhitaker ping

**Comment by simonwhitaker** [comment]
![dont know how](https://cloud.githubusercontent.com/assets/116432/23601507/b6f9acc4-0243-11e7-8d48-f24584c36124.gif)

I've never actually used Bower. I've just created and pushed a 0.2.1 tag, let's see if that works.

**Comment by simonwhitaker** [comment]
Yeah, looks like that worked.

```
$ bower install github-fork-ribbon-css
bower github-fork-ribbon-css#*  cached https://github.com/simonwhitaker/github-fork-ribbon-css.git#0.2.1
bower github-fork-ribbon-css#*         validate 0.2.1 against https://github.com/simonwhitaker/github-fork-ribbon-css.git#*
bower github-fork-ribbon-css#^0.2.1     install github-fork-ribbon-css#0.2.1

github-fork-ribbon-css#0.2.1 bower_components/github-fork-ribbon-css
```

**Comment by JPeer264** [comment]
awesome mate - thanks 👍
