### ISSUE TITLE
Instant copy-paste

### ISSUE THREAD

**Issue by neersighted** [simonwhitaker/github-fork-ribbon-css#6]
Editing the `index.html` file to serve the CSS off of `raw.github.com` would me people would not need the asset locally, but would mean that if Github goes down, so does the ribbon. Thoughts?

**Comment by simonwhitaker** [comment]
I had the same thought – basically that you could use GitHub as a rough-and-ready Content Delivery Network (CDN). However, I did some investigation and it sounds as though hosting from `raw.github.com` is [not the way to go](http://stackoverflow.com/a/5503156/263871).

A Google search on "github as cdn" comes up with [GitHub as a CDN](http://code.lancepollard.com/github-as-a-cdn/), which suggests using Google Pages as a CDN. That looks like it'd work better (it sets an HTTP Expires header that's 24 hours from now), but not sure if it's what you'd expect (or want) from a proper CDN. See below for HTTP headers from a call to raw.github.com, a call to the corresponding Github Pages URL, and (for comparison) a call to the Google CDN link for jQuery 1.8.0.

```
$ curl -s -o /dev/null -D - https://raw.github.com/simonwhitaker/github-fork-ribbon-css/master/gh-fork-ribbon.css
HTTP/1.1 200 OK
Server: nginx/1.0.13
Date: Wed, 29 Aug 2012 13:20:57 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Status: 200 OK
X-Frame-Options: deny
X-RateLimit-Remaining: 100
Content-Transfer-Encoding: binary
X-RateLimit-Limit: 100
ETag: "82998edc12e52d04f393ca2c79dd757c"
Content-Length: 2732
Cache-Control: private
X-Runtime: 10
X-Content-Type-Options: nosniff
Content-Disposition: inline

$ curl -s -o /dev/null -D - http://simonwhitaker.github.com/github-fork-ribbon-css/gh-fork-ribbon.css
HTTP/1.1 200 OK
Server: nginx/1.0.13
Date: Wed, 29 Aug 2012 13:21:02 GMT
Content-Type: text/css
Content-Length: 2732
Last-Modified: Wed, 29 Aug 2012 04:05:50 GMT
Connection: keep-alive
Expires: Thu, 30 Aug 2012 13:21:02 GMT
Cache-Control: max-age=86400
Accept-Ranges: bytes

$ curl -s -o /dev/null -D - https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js
HTTP/1.1 200 OK
Vary: Accept-Encoding
Content-Type: text/javascript; charset=UTF-8
Last-Modified: Fri, 10 Aug 2012 20:05:59 GMT
Date: Thu, 23 Aug 2012 01:57:22 GMT
Expires: Fri, 23 Aug 2013 01:57:22 GMT
X-Content-Type-Options: nosniff
Server: sffe
X-XSS-Protection: 1; mode=block
Cache-Control: public, max-age=31536000
Age: 559468
Transfer-Encoding: chunked
```

**Comment by simonwhitaker** [comment]
So in short, I'm going to close this issue. It's OK to let people grab the assets for themselves for the time being.

**Comment by neersighted** [comment]
@simonwhitaker One other possibility is serving it off Heroku (AWS East 2), using my [nginx build pack](https://github.com/neersighted/heroku-buildpack-nginx).
