### ISSUE TITLE
Release 0.2.2 to NPM

### ISSUE THREAD

**Issue by bkimminich** [simonwhitaker/github-fork-ribbon-css#61]
Hi @simonwhitaker! It seems on NPM your latest version is still 0.2.1, which does not use the `data-ribbon` but `title` and - at least for me - has text alignment issues. As a workaround I'm declaring dependency on your project as

```
"github-fork-ribbon-css": "simonwhitaker/github-fork-ribbon-css#0.2.2"
```

but it would be nice to be able to go back to

```
"github-fork-ribbon-css": "~0.2"
```

at some point. Thanks in advance! Best ribbon ever! 🥇

**Comment by brettz9** [comment]
Yes, please just submit a new `npm publish` for us! Thanks!

**Comment by bkimminich** [comment]
🧟‍♂️ We stopped using this module at least 1 year ago. Thanks anyway!

**Comment by brettz9** [comment]
That's fine for you, but I'd still like it!

**Comment by simonwhitaker** [comment]
Hi! So sorry, I managed to miss this one for a year and a half! 😬 

It turns out, I don't even own the NPM package. Someone else created that on my behalf around 3 years ago. I've emailed them to ask if they could transfer the package to me, then I can update it. (Alternatively, I'll ask them to update it themselves.) Sorry for the very, very, very long delay!

**Comment by simonwhitaker** [comment]
Here we go:

https://github.com/simonwhitaker/github-fork-ribbon-css/issues/52

@swervo - I emailed you my npm details earlier. Would you mind transferring the NPM package to me please? (And thank you so much for publishing it in the first place! I'm rubbish at these things, as this issue amply demonstrates.)

**Comment by hugovk** [comment]
When sorted, maybe also do a new 0.2.3 release, there've been a few changes since 0.2.2:

https://github.com/simonwhitaker/github-fork-ribbon-css/compare/0.2.2...gh-pages

(Might be an idea to put both 0.2.2 and 0.2.3 on npm, just in case someone really needs 0.2.2 via npm.)

**Comment by simonwhitaker** [comment]
Good call @hugovk, will do!

**Comment by swervo** [comment]
@simonwhitaker it's all yours. I've added you as a maintainer (ie., owner) so you should be able to take control. Thanks. Dom

**Comment by simonwhitaker** [comment]
Thanks Dom!

**Comment by simonwhitaker** [comment]
OK, 0.2.2 and 0.2.3 now published.
