### ISSUE TITLE
Black ribbon in print with Safari

### ISSUE THREAD

**Issue by mmagnus** [simonwhitaker/github-fork-ribbon-css#66]
Hmm.. although in the preview Safari says that the ribbon will be read when I print it's black. Do you have any idea what the problem can be?
<img width="694" alt="screen shot 2018-08-08 at 12 07 58 pm" src="https://user-images.githubusercontent.com/118740/43831274-dc5a1486-9b03-11e8-95ce-c43c4569e39f.png">
<img width="251" alt="screen shot 2018-08-08 at 12 07 46 pm" src="https://user-images.githubusercontent.com/118740/43831277-dd41919e-9b03-11e8-8acf-aa8241063457.png">

**Comment by mmagnus** [comment]
<img width="1129" alt="screen shot 2018-08-08 at 12 13 35 pm" src="https://user-images.githubusercontent.com/118740/43831459-7fbc70b0-9b04-11e8-8e28-6dd98395270f.png">
Also in the freshest version of the repo, it didn't work.

**Comment by warengonzaga** [comment]
I guess the problem is with your printer? It shouldn't be black.

**Comment by mmagnus** [comment]
No, no. This is even in a PDF. So, on the Print to PDF preview page (in Safari), this is red, but in an actual PDF file, it's black. Exactly as I showed before. This is from today:

<img width="319" alt="Screen Shot 2020-11-02 at 9 09 50 PM" src="https://user-images.githubusercontent.com/118740/97914300-f41b8c00-1d4f-11eb-8f64-123e000a3344.png">
<img width="852" alt="Screen Shot 2020-11-02 at 9 09 59 PM" src="https://user-images.githubusercontent.com/118740/97914315-f8e04000-1d4f-11eb-841f-318c6a6c2f79.png">

**Comment by warengonzaga** [comment]
@mmagnus I'm gonna work on it expect my PR for this issue.

**Comment by warengonzaga** [comment]
Hi @mmagnus can you please confirm the fix from my latest PR #71 thank you!

**Comment by mmagnus** [comment]
Hey, thanks for your work.

Yeah, I  got this version:

     (py37) [mx] github-fork-ribbon-css-pr$ git:(pr/71) open index.html

but the ribbon is still black:

<img width="1050" alt="Screen Shot 2020-11-09 at 9 31 33 PM" src="https://user-images.githubusercontent.com/118740/98593206-1de62d00-22d3-11eb-9bc4-42a44f67a427.png">
