### ISSUE TITLE
Bundle minified version

### ISSUE THREAD

**Issue by brettz9** [simonwhitaker/github-fork-ribbon-css#70]
Hi,

I don't know if you prepared this minified version, but one is available at https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css , and as I'd like to be able to get a local copy which matches the integrity of the CDN copy, it'd be nice if I could get this bundle with the npm release. Do you think you could bundle a minified copy?

**Comment by brettz9** [comment]
Or do you want a minifying process of some kind added to npm?

**Comment by warengonzaga** [comment]
@brettz9 I guess I can work on that... I will submit a PR. Thank you!

**Comment by brettz9** [comment]
FWIW, I am using https://github.com/brettz9/integrity-matters to confirm that the integrity of any given npm package copy is what is listed in one's HTML `integrity` attributes (or JS/JSON). It's an added protection of not just trusting what someone says the integrity is (and npm package content would presumably be less subject to manipulation and discoverable for vulnerabilities, etc.).

**Comment by warengonzaga** [comment]
> FWIW, I am using https://github.com/brettz9/integrity-matters to confirm that the integrity of any given npm package copy is what is listed in one's HTML `integrity` attributes (or JS/JSON). It's an added protection of not just trusting what someone says the integrity is (and npm package content would presumably be less subject to manipulation and discoverable for vulnerabilities, etc.).

Awesome thanks for the guide I'll review it... and let you know or I will suggest a better approach to that.

**Comment by brettz9** [comment]
Sure. And just to be clear that tool is not something for use within a PR here--just for users who can be assured that they can automatically enforce on the attribute for their CDN the same integrity as the miniifed file you have given in npm.
