### ISSUE TITLE
Add color overrides to Usage

### ISSUE THREAD

**Issue by tony--** [simonwhitaker/github-fork-ribbon-css#72]
For the style-challenged among us, such as myself, please add a color override example to the Usage section.
e.g.,
`    <style>
        .github-fork-ribbon.right-top:before {
            background-color: #333;
        }
    </style>`

It would have saved me 15 minutes.
Thanks!

**Comment by hugovk** [comment]
Good idea, please see PR https://github.com/simonwhitaker/github-fork-ribbon-css/pull/73.

**Comment by simonwhitaker** [comment]
Thanks Hugo!
