### ISSUE TITLE
[Question] Push it more to the corner

### ISSUE THREAD

**Issue by ghost** [simonwhitaker/github-fork-ribbon-css#75]
Hi,
I'm sorry that I couldn't help it with CSS as I know very little about so this is rather a question if you may.
Probably not the common usage or taste, but I would like to push it more to the corner to let other elements (footer especially) be displayed.
First I set it's z-index to 0 as I don't want it to be on top of other elements.
Second I want to push it more to the corner, and if possible make it like a small icon or a triangle rather than a ribbon
This is the capture
![image](https://user-images.githubusercontent.com/10267332/218252844-9c251146-3b70-4026-8e29-438b71ddd112.png)

My preferred solution would be as minimal as possible, setting GitHub icon would be better and as a rectangle or a triangle.
If I need to keep it as a ribbon, I would like only the ribbon to be clickable and not a whole rectangle behind.

Thanks a lot

**Comment by hugovk** [comment]
At least for the top-right ribbon, you can reduce the `top` and `right` values into the negative to move it into the corner.

But maybe https://tholman.com/github-corners/ suit you better?

**Comment by ghost** [comment]
@hugovk thanks a lot for your response!
indeed I guess the corners solution suits my case. 
kindly
