### ISSUE TITLE
Clipping bug on Safari for iOS

### ISSUE THREAD

**Issue by simonwhitaker** [simonwhitaker/github-fork-ribbon-css#8]
On Safari for iOS it's possible to scroll past the right hand edge of the page, revealing the "hidden" corner of the ribbon.

![Screenshot](http://cloud.goosoftware.co.uk/J5AX/Screen%20Shot%202012-08-29%20at%2008.06.49.png)

**Comment by neersighted** [comment]
I'll look into it more, I have an iPad handy.

**Comment by neersighted** [comment]
Said bug also exists in (Ubuntu) Chrome and Firefox.

The scrollbar does not show up, but by scrolling (I have a mouse with right/left scrolling) to the right, you will see the edge of the ribbon.
